baseURL: 'http://kjczarne.github.io/'
languageCode: 'en-us'
title: 'Klebstoff'
theme: 'PaperMod'


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search


params:
  homeInfoParams:
    Title: Klebstoff
    Content: >
      **Krzysztof J. Czarnecki**'s Blog
  ShowCodeCopyButtons: true

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/kjczarne"
    - name: "email"
      url: "mailto://kjczarne@gmail.com"
    - name: "medium"
      url: "https://medium.com/@krzysztofczarnecki"
    - name: "buymeacoffee"
      url: "https://www.buymeacoffee.com/kjczarne"

  fuseOpts:  # Fuse.JS Search
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


menu:
  main:
  - identifier: search
    name: search
    url: /search/
    weight: 2
  - identifier: tags
    name: tags
    url: /tags/
    weight: 3
  - identifier: posts
    name: posts
    url: /posts/
    weight: 1
  - identifier: about
    name: about
    url: /about/
    weight: 5
