baseURL = "http://kjczarne.github.io/"
languageCode = "en-us"
title = "Chris"
theme = "PaperMod"
disqusShortname = "kjczarne"
copyright = """
&copy; 2024 Chris J. Czarnecki. Fair use permitted with authorship attribution. Commercial use disallowed without explicit permission. Some links in blog articles are affiliate links when noted.
"""

name = "Chris J. Czarnecki"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
math = true
ShowShareButtons = true
ShowReadingTime = true
ShowCodeCopyButtons = true
comments = true
showtoc = true

  [params.homeInfoParams]
  Title = "Chris"
  Content = """
**Krzysztof J. Czarnecki**'s Blog
"""

  [params.profileMode]
  enabled = true
  title = "Chris J. Czarnecki"
  subtitle = "**Biotech -> SWE -> AI**"
  imageUrl = "/k.png"
  imageTitle = "<title of image as alt>"
  imageWidth = 2000
  imageHeight = 800

    [[params.profileMode.buttons]]
    name = "brainfarts"
    url = "/posts"

    [[params.profileMode.buttons]]
    name = "CV"
    url = "/cv"

    [[params.profileMode.buttons]]
    name = "Papers"
    url = "/papers"

    # [params.profileMode.newsletter]
    # name = "TinyLetter"
    # url = "https://tinyletter.com/kjczarne"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/kjczarne"

  [[params.socialIcons]]
  name = "email"
  url = "mailto://kjczarne@gmail.com"

  [[params.socialIcons]]
  name = "google scholar"
  url = "https://scholar.google.com/citations?user=WPVIuxMAAAAJ&hl=en"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://scholar.google.com/citations?user=WPVIuxMAAAAJ&hl=en"

#   [[params.socialIcons]]
#   name = "medium"
#   url = "https://medium.com/@krzysztofczarnecki"

#   [[params.socialIcons]]
#   name = "buymeacoffee"
#   url = "https://www.buymeacoffee.com/kjczarne"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

# [cover]
# image = "/3c.png"
# alt = "logo"
# relative = true

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 2

# [[menu.main]]
# identifier = "tags"
# name = "tags"
# url = "/tags/"
# weight = 3

# [[menu.main]]
# identifier = "categories"
# name = "categories"
# url = "/categories/"
# weight = 4

[[menu.main]]
identifier = "posts"
name = "brainfarts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 5

[[menu.main]]
identifier = "cv"
name = "cv"
url = "/cv/"
weight = 4

[[menu.main]]
identifier = "papers"
name = "papers"
url = "/papers/"
weight = 3
