baseURL: 'http://kjczarne.github.io/'
languageCode: 'en-us'
title: 'Klebstoff'
theme: 'PaperMod'
disqusShortname: kjczarne

permalinks:
  posts: /:year-:month-:day-:title/

author:
  name: Krzysztof J. Czarnecki
copyright: >
  Copyright 2021 Krzysztof J. Czarnecki. Fair use permitted with authorship
  attribution. Commercial use disallowed without explicit permission.

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search


params:
  ShowShareButtons: true
  ShowReadingTime: true
  homeInfoParams:
    Title: Klebstoff
    Content: >
      **Krzysztof J. Czarnecki**'s Blog
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: "Klebstoff" # optional default will be site title
    subtitle: "**Krzysztof J. Czarnecki**"
    imageUrl: "/me.jfif" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 300 # custom size
    imageHeight: 300 # custom size
    buttons:
      - name: Blog
        url: "/posts"
    newsletter:
      name: TinyLetter
      url: https://tinyletter.com/kjczarne

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/kjczarne"
    - name: "email"
      url: "mailto://kjczarne@gmail.com"
    - name: "medium"
      url: "https://medium.com/@krzysztofczarnecki"
    - name: "buymeacoffee"
      url: "https://www.buymeacoffee.com/kjczarne"

  fuseOpts:  # Fuse.JS Search
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
  comments: true


cover:
  image: "/static/3c.png"
  # can also paste direct link from external site
  # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
  alt: "logo"
  relative: true # To use relative path for cover image, used in hugo Page-bundles

menu:
  main:
  - identifier: search
    name: search
    url: /search/
    weight: 2
  - identifier: tags
    name: tags
    url: /tags/
    weight: 3
  - identifier: categories
    name: categories
    url: /categories/
    weight: 4
  - identifier: posts
    name: posts
    url: /posts/
    weight: 1
  - identifier: about
    name: about
    url: /about/
    weight: 5
